name: Build and deploy

on:
  push:
    branches: [main, TASKS-547]
  workflow_dispatch:

env:
  IMAGE: partnersinhealth/openmrs-distro-pihsl
  DOCKER_IMAGE_PLATFORMS: linux/amd64,linux/arm64

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build and Publish
    if: github.repository_owner == 'PIH'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'maven'
          server-id: central
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD

      - name: Maven Deploy
        run: mvn -B -U deploy --file pom.xml
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Extract pom version
        run: echo "DOCKER_IMAGE_TAG_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: pihci
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: target/distro/web
          push: true
          platforms: ${{ env.DOCKER_IMAGE_PLATFORMS }}
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.DOCKER_IMAGE_TAG_VERSION }}
